global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "aggregator"
    static_configs:
      - targets: ["aggregator:8080"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]
