name: "yolov8s"
platform: "onnxruntime_onnx"
max_batch_size: 128

input [{
  name: "images"
  data_type: TYPE_FP32
  dims: [3, 640, 640]
 }]

output [{
   name: "output0"
   data_type: TYPE_FP32
  dims: [-1, -1]
}]

dynamic_batching {
  preferred_batch_size: [16, 32, 64]
  max_queue_delay_microseconds: 25000
}

instance_group [{
  count: 1
  kind: KIND_GPU
}]
